Update temp.yaml

diff --git a/.github/workflows/temp.yaml b/.github/workflows/temp.yaml
--- a/.github/workflows/temp.yaml
+++ b/.github/workflows/temp.yaml
@@ -5,10 +5,17 @@ jobs:
   label_issues:
     runs-on: ubuntu-latest
     steps:
-      - name: Output command context
-        env:
-          COMMAND_CONTEXT: ${{ toJSON(github.event) }}
-        run: echo "$COMMAND_CONTEXT"
-      - name: pring
-        run: echo "known $GITHUB_REF job $GITHUB_JOB"
+#       - name: Output command context
+#         env:
+#           COMMAND_CONTEXT: ${{ toJSON(github.event) }}
+#         run: echo "$COMMAND_CONTEXT"
+      - name: first
+        run: exit 1
+        continue-on-error: true
+      - name: The job has failed
+        if: ${{ failure() }}
+        run: echo "failed"
+      - name: The job has failed
+        if: ${{ success() }}
+        run: echo "success"
 
